linters:
    disable-all: true
    enable:
    - bodyclose
    - deadcode
    - errcheck
    - gochecknoglobals
    - goconst
    - gocritic
    - gofmt
    - goimports
    - golint
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - maligned
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - wsl
    - godot

  # don't enable:
  # - depguard
  # - dogsled
  # - dupl
  # - funlen
  # - gochecknoinits
  # - gocognit
  # - gocyclo
  # - godox
  # - gomnd
  # - lll
  # - rowserrcheck
  # - scopelint


issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

    - linters:
        - errcheck
      source: ".((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv)."

    - linters:
        - stylecheck
      text: "ST1003:.*(Ts|ts).*TS"

#     - linters:
#         - lll
#       source: "^(func|type|struct)"

  exclude-use-default: false


service:
  golangci-lint-version: 1.24.x
