package object // import "github.com/SevereCloud/vksdk/5.92/object"

// Error codes. See https://vk.com/dev/errors
const (
	ErrorUnknown                           = 1    // Unknown error occurred
	ErrorDisabled                          = 2    // Application is disabled. Enable your application or use test mode
	ErrorMethod                            = 3    // Unknown method passed
	ErrorSignature                         = 4    // Incorrect signature
	ErrorAuth                              = 5    // User authorization failed
	ErrorTooMany                           = 6    // Too many requests per second
	ErrorPermission                        = 7    // Permission to perform this action is denied
	ErrorRequest                           = 8    // Invalid request
	ErrorFlood                             = 9    // Flood control
	ErrorServer                            = 10   // Internal server error
	ErrorEnabledInTest                     = 11   // In test mode application should be disabled or user should be authorized
	ErrorCaptcha                           = 14   // Captcha needed
	ErrorAccess                            = 15   // Access denied
	ErrorAuthHTTPS                         = 16   // HTTP authorization failed
	ErrorAuthValidation                    = 17   // Validation required
	ErrorUserDeleted                       = 18   // User was deleted or banned
	ErrorBlocked                           = 19   // Content blocked
	ErrorMethodPermission                  = 20   // Permission to perform this action is denied for non-standalone applications
	ErrorMethodAds                         = 21   // Permission to perform this action is allowed only for standalone and OpenAPI applications
	ErrorUpload                            = 22   // Upload error
	ErrorMethodDisabled                    = 23   // This method was disabled
	ErrorNeedConfirmation                  = 24   // Confirmation required
	ErrorNeedTokenConfirmation             = 25   // Token confirmation required
	ErrorGroupAuth                         = 27   // Group authorization failed
	ErrorAppAuth                           = 28   // Application authorization failed
	ErrorRateLimit                         = 29   // Rate limit reached
	ErrorPrivateProfile                    = 30   // This profile is private
	ErrorParam                             = 100  // One of the parameters specified was missing or invalid
	ErrorParamAPIID                        = 101  // Invalid application API ID
	ErrorLimits                            = 103  // Out of limits
	ErrorNotFound                          = 104  // Not found
	ErrorSaveFile                          = 105  // Couldn't save file
	ErrorActionFailed                      = 106  // Unable to process action
	ErrorParamUserID                       = 113  // Invalid user id
	ErrorParamAlbumID                      = 114  // Invalid album id
	ErrorParamServer                       = 118  // Invalid server
	ErrorParamTitle                        = 119  // Invalid title
	ErrorParamPhotos                       = 122  // Invalid photos
	ErrorParamHash                         = 121  // Invalid hash
	ErrorParamPhoto                        = 129  // Invalid photo
	ErrorParamGroupID                      = 125  // Invalid group id
	ErrorParamPageID                       = 140  // Page not found
	ErrorAccessPage                        = 141  // Access to page denied
	ErrorMobileNotActivated                = 146  // The mobile number of the user is unknown
	ErrorInsufficientFunds                 = 147  // Application has insufficient funds
	ErrorAccessMenu                        = 148  // Access to the menu of the user denied
	ErrorParamTimestamp                    = 150  // Invalid timestamp
	ErrorFriendsListID                     = 171  // Invalid list id
	ErrorFriendsListLimit                  = 173  // Reached the maximum number of lists
	ErrorFriendsAddYourself                = 174  // Cannot add user himself as friend
	ErrorFriendsAddInEnemy                 = 175  // Cannot add this user to friends as they have put you on their blacklist
	ErrorFriendsAddEnemy                   = 176  // Cannot add this user to friends as you put him on blacklist
	ErrorFriendsAddNotFound                = 177  // Cannot add this user to friends as user not found
	ErrorParamNoteID                       = 180  // Note not found
	ErrorAccessNote                        = 181  // Access to note denied
	ErrorAccessNoteComment                 = 182  // You can't comment this note
	ErrorAccessComment                     = 183  // Access to comment denied
	ErrorAccessAlbum                       = 200  // Access denied
	ErrorAccessAudio                       = 201  // Access denied
	ErrorAccessGroup                       = 203  // Access to group denied
	ErrorAccessVideo                       = 204  // Access denied
	ErrorAccessMarket                      = 205  // Access denied
	ErrorWallAccessPost                    = 210  // Access to wall's post denied
	ErrorWallAccessComment                 = 211  // Access to wall's comment denied
	ErrorWallAccessReplies                 = 212  // Access to post comments denied
	ErrorWallAccessAddReply                = 213  // Access to status replies denied
	ErrorWallAddPost                       = 214  // Access to adding post denied
	ErrorWallAdsPublished                  = 219  // Advertisement post was recently added
	ErrorWallTooManyRecipients             = 220  // Too many recipients
	ErrorStatusNoAudio                     = 221  // User disabled track name broadcast
	ErrorWallLinksForbidden                = 222  // Hyperlinks are forbidden
	ErrorWallReplyOwnerFlood               = 223  // Too many replies
	ErrorWallAdsPostLimitReached           = 224  // Too many ads posts
	ErrorPollsAccess                       = 250  // Access to poll denied
	ErrorPollsAnswerID                     = 252  // Invalid answer id
	ErrorPollsPollID                       = 251  // Invalid poll id
	ErrorPollsAccessWithoutVote            = 253  // Access denied, please vote first
	ErrorAccessGroups                      = 260  // Access to the groups list is denied due to the user's privacy settings
	ErrorAlbumFull                         = 300  // This album is full
	ErrorAlbumsLimit                       = 302  // Albums number limit is reached
	ErrorVotesPermission                   = 500  // Permission denied. You must enable votes processing in application settings
	ErrorVotes                             = 503  // Not enough votes
	ErrorAdsPermission                     = 600  // Permission denied. You have no access to operations specified with given object(s)
	ErrorWeightedFlood                     = 601  // Permission denied. You have requested too many actions this day. Try later
	ErrorAdsPartialSuccess                 = 602  // Some part of the request has not been completed
	ErrorAdsSpecific                       = 603  // Some ads error occurred
	ErrorAdsObjectDeleted                  = 629  // Object deleted
	ErrorGroupChangeCreator                = 700  // Cannot edit creator role
	ErrorGroupNotInClub                    = 701  // User should be in club
	ErrorGroupTooManyOfficers              = 702  // Too many officers in club
	ErrorGroupNeed2fa                      = 703  // You need to enable 2FA for this action
	ErrorGroupHostNeed2fa                  = 704  // User needs to enable 2FA for this action
	ErrorGroupTooManyAddresses             = 706  // Too many addresses in club
	ErrorVideoAlreadyAdded                 = 800  // This video is already added
	ErrorVideoCommentsClosed               = 801  // Comments for this video are closed
	ErrorMessagesUserBlocked               = 900  // Can't send messages for users from blacklist
	ErrorMessagesDenySend                  = 901  // Can't send messages for users without permission
	ErrorMessagesPrivacy                   = 902  // Can't send messages to this user due to their privacy settings
	ErrorMessagesTooOldPts                 = 907  // Value of ts or pts is too old
	ErrorMessagesTooNewPts                 = 908  // Value of ts or pts is too new
	ErrorMessagesEditExpired               = 909  // Can't edit this message, because it's too old
	ErrorMessagesTooBig                    = 910  // Can't sent this message, because it's too big
	ErrorMessagesKeyboardInvaliD           = 911  // Keyboard format is invalid
	ErrorMessagesChatBotFeature            = 912  // This is a chat bot feature, change this status in settings
	ErrorMessagesTooLongForwards           = 913  // Too many forwarded messages
	ErrorMessagesTooLongMessage            = 914  // Message is too long
	ErrorMessagesChatUserNoAccess          = 917  // You don't have access to this chat
	ErrorMessagesCantSeeInviteLink         = 919  // You can't see invite link for this chat
	ErrorMessagesEditKindDisallowed        = 920  // Can't edit this kind of message
	ErrorMessagesCantFwd                   = 921  // Can't forward these messages
	ErrorMessagesCantDeleteForAll          = 924  // Can't delete this message for everybody
	ErrorMessagesChatNotAdmin              = 925  // You are not admin of this chat
	ErrorMessagesChatNotExist              = 927  // Chat does not exist
	ErrorMessagesCantChangeInviteLink      = 931  // You can't change invite link for this chat
	ErrorMessagesGroupPeerAccess           = 932  // Your community can't interact with this peer
	ErrorMessagesChatUserNotInChat         = 935  // User not found in chat
	ErrorMessagesContactNotFound           = 936  // Contact not found
	ErrorMessagesMessageRequestAlreadySend = 939  // Message request already send
	ErrorParamPhone                        = 1000 // Invalid phone number
	ErrorPhoneAlreadyUsed                  = 1004 // This phone number is used by another user
	ErrorAuthFloodError                    = 1105 // Too many auth attempts, try again later
	ErrorAuthDelay                         = 1112 // Processing.. Try later
	ErrorParamDocID                        = 1150 // Invalid document id
	ErrorParamDocDeleteAccess              = 1151 // Access to document deleting is denied
	ErrorParamDocTitle                     = 1152 // Invalid document title
	ErrorParamDocAccess                    = 1153 // Access to document is denied
	ErrorPhotoChanged                      = 1160 // Original photo was changed
	ErrorTooManyLists                      = 1170 // Too many feed lists
	ErrorAppsAlreadyUnlocked               = 1251 // This achievement is already unlocked
	ErrorAppsSubscriptionNotFound          = 1256 // Subscription not found
	ErrorAppsSubscriptionInvalidStatus     = 1257 // Subscription is in invalid status
	ErrorInvalidAddress                    = 1260 // Invalid screen name
	ErrorCommunitiesCatalogDisabled        = 1310 // Catalog is not available for this user
	ErrorCommunitiesCategoriesDisabled     = 1311 // Catalog categories are not available for this user
	ErrorMarketRestoreTooLate              = 1400 // Too late for restore
	ErrorMarketCommentsClosed              = 1401 // Comments for this market are closed
	ErrorMarketAlbumNotFound               = 1402 // Album not found
	ErrorMarketItemNotFound                = 1403 // Item not found
	ErrorMarketItemAlreadyAdded            = 1404 // Item already added to album
	ErrorMarketTooManyItems                = 1405 // Too many items
	ErrorMarketTooManyItemsInAlbum         = 1406 // Too many items in album
	ErrorMarketTooManyAlbums               = 1407 // Too many albums
	ErrorMarketItemHasBadLinks             = 1408 // Item has bad links in description
	ErrorStoryExpired                      = 1600 // Story has already expired
	ErrorStoryIncorrectReplyPrivacy        = 1602 // Incorrect reply privacy
	ErrorPrettyCardsCardNotFound           = 1900 // Card not found
	ErrorPrettyCardsTooManyCards           = 1901 // Too many cards
	ErrorPrettyCardsCardIsConnectedToPost  = 1902 // Card is connected to post
	ErrorCallbackServersLimit              = 2000 // Servers number limit is reached
)
